services:
  app1:
    build: .
    image: expressify-server
    container_name: app1_server
    environment:
      - instance_ID=1
      - PORT=3000

  app2:
    build: .
    image: expressify-server
    container_name: app2_server
    environment:
      - instance_ID=2
      - PORT=3001

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
